source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks! :linkage => :static

workspace '../RoxieMobile.ContentProviders/ContentProviders.xcworkspace'


# MARK: - Sources

target 'ContentProviders.SQLite' do
  project '../RoxieMobile.ContentProviders/Sources/SQLite/ContentProviders.SQLite.xcodeproj'

  # Dependencies
  pod 'CryptoSwift', '~> 1.3.8'
  pod 'GRDB.swift/SQLCipher', '~> 5.7.4'
  pod 'SwiftCommons/Concurrent', '~> 1.6.0'
  pod 'SwiftCommons/Extensions', '~> 1.6.0'
  pod 'ZIPFoundation', '~> 0.9.12'
end
